on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
      - name: Installing Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'
      - name: Config git user & email
        run: |
          git config user.name "$(git log -n 1 --pretty=format:%an)"
          git config user.email "$(git log -n 1 --pretty=format:%ae)"
      - name: Run my Action
        id: run-action
        uses: iuccio/npm-semver-publish-action@v1.0.0
        with:
          target-branch: master
          provenance: true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}